env: "debug" # may be text
storage_path: "user=postgres password=postgres dbname=postgres sslmode=disable" #user, password, DB name
http_server:
  address: "localhost:8000"
  timeout: 4s
  idle_timeout: 60s